patterns:
  - files:
      - from: sync/mergify.yml
        to: .github/mergify.yml
    pull_request:
      disabled: false
      force: true
      title: "chore: sync mergify config"
    repositories:
      - trim21/neptune
      - trim21/imagesync
      - trim21/python-build-standalone-container-mirror
      - trim21/rdfind2
      - trim21/china-beancount-importers
      - trim21/action-uv-lock-diff-viewer
      - trim21/php-serialize
      - trim21/crontab
      - trim21/bencode-py
      - trim21/sslog
      - trim21/downloader-prom-exporter
      - trim21/snakefood3
      - trim21/asio-loop
      - trim21/count
      - trim21/rfc3986-stubs
      - trim21/bangumi-episode-calendar
      - trim21/bgm-tv-userscripts
      - trim21/pypika-stubs
      - trim21/transmission-rpc
      - trim21/blog
      - trim21/renovate-config
      - trim21/mt-mediainfo
      - trim21/gm-fetch
      - trim21/userscript-metadata-webpack-plugin
      - trim21/php-serialize-py
      - trim21/userscript-metadata-generator
      - trim21/pypi-feedstocks
      - trim21/webpack-userscript-template
      - trim21/dprint-pre-commit
      - trim21/dprint-py
      - trim21/pre-commit-mirror-meson
      - trim21/wcwidth-stubs
      - trim21/conda-channel-mirrors
      - trim21/scoop-bucket
      - trim21/bencode-rs
      - trim21/qbittorrent-feedstock
      - trim21/bangumi-pages
      - trim21/renovate
      - trim21/changelog-previous-tag
      - trim21/flood-apt-repo
      - trim21/try
      - trim21/libvalkey-feedstock-1
      - trim21/bep14
      - trim21/rtorrent-rpc
      - trim21/master-degree-final
      - trim21/meilisearch-prom-exporter
      - trim21/ruff-feedstock
      - trim21/asyncpg-stubs
      - trim21/gopeed
      - trim21/pixi
      - trim21/actions
      - trim21/minio-client-feedstock
      - trim21/trim21
      - trim21/pkg
      - trim21/qt-main-feedstock
      - trim21/flood
      - trim21/rattler-build-feedstock
      - trim21/pt-repost
      - trim21/go-phpserialize
      - trim21/go-bencode
      - trim21/rattler-build-action
      - trim21/go-task-feedstock
      - trim21/thesis
      - trim21/axoasset
      - trim21/Extras
      - trim21/staged-recipes
      - trim21/htest
      - trim21/search
      - trim21/atomic
      - trim21/uuid-utils
      - trim21/BGmi
      - trim21/rattler-build
      - trim21/mediainfo-feedstock
      - trim21/maturin-feedstock
      - trim21/conda-smithy
      - trim21/conda-build
      - trim21/maturin
      - trim21/pyo3
      - trim21/MediaInfo
      - trim21/actionlint
      - trim21/durationpy
      - trim21/MediaInfoLib
      - trim21/valkey-py-feedstock
      - trim21/libvalkey-py-feedstock
      - trim21/rust-activation-feedstock
      - trim21/xsync
      - trim21/mirror-to-gitea
      - trim21/Main
      - trim21/yarl
      - trim21/setup-task
      - trim21/server
      - trim21/packaging
      - trim21/valkey-py
      - trim21/libvalkey-feedstock
      - trim21/libvalkey
      - trim21/psycopg2-feedstock
      - trim21/rattler
      - trim21/errgo
      - trim21/bangumi-server-private
      - trim21/zerolog
