name: Sync Files
on:
  push:
    branches:
      - master
    paths:
      - sync/**
      - .github/files-sync-config.yaml
      - .github/workflows/sync-files.yaml
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: wadackel/files-sync-action@v3
        with:
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
