name: test

on:
  push:

jobs:
  main:
    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v4
        with:
          repository: prefix-dev/rattler-build

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo build
